version: 2

sources:
  - name: raw
    database: dwh
    tables:
      - name: devices
      - name: stores
      - name: transactions
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: ingested_at

